arb-dir: lib\l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false
gen-inputs-and-outputs-list: lib/l10n
untranslated-messages-file: l10n_errors.txt
