name: patternpod
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  bot_toast: ^4.0.3
  cached_network_image: ^3.2.2
  cupertino_icons: ^1.0.2
  dropdown_button2: ^2.0.0
  equatable: ^2.0.5
  flex_color_scheme: ^7.0.5
  flutter:
    sdk: flutter
  flutter_easylogger: ^2.3.3
  flutter_hooks: ^0.20.0
  flutter_inappwebview: ^5.7.2+3
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.5.4
  flutter_speed_dial: ^7.0.0
  flutter_spinkit: ^5.1.0
  form_validator: ^2.1.1
  fpdart: ^1.0.0
  gap: ^3.0.0
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.0.2
  icons_plus: ^4.0.0
  intl: ^0.18.0
  modal_bottom_sheet: ^3.0.0-pre
  readmore: ^2.2.0
  rive: ^0.11.1
  timelines: ^0.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
  fonts:
    - family: baiJamjuree
      fonts:
        - asset: assets/fonts/BaiJamjuree-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/BaiJamjuree-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/BaiJamjuree-Light.ttf
          weight: 300
        - asset: assets/fonts/BaiJamjuree-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/BaiJamjuree-Italic.ttf
          style: italic
        - asset: assets/fonts/BaiJamjuree-Regular.ttf
          weight: 400
        - asset: assets/fonts/BaiJamjuree-Medium.ttf
          weight: 500
        - asset: assets/fonts/BaiJamjuree-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/BaiJamjuree-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BaiJamjuree-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/BaiJamjuree-Bold.ttf
          weight: 700
        - asset: assets/fonts/BaiJamjuree-BoldItalic.ttf
          style: italic
          weight: 700
